apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 65.2.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-charts
        namespace: flux-system
  values:
    grafana:
      enabled: false
    prometheus:
      service:
        type: NodePort
  valuesFrom:
    - kind: ConfigMap
      name: kube-prometheus-stack-alertmanager-configmap
      valuesKey: values.yaml
      optional: false
