---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 64.0.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-charts
        namespace: flux-system
  values:
    grafana:
      enabled: false
