apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 68.5.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-charts
        namespace: flux-system
  values:
    grafana:
      enabled: false
    prometheus:
      service:
        type: NodePort
    # Until an external secrets operator is implemented
    # Alertmanager needs to be disabled and enabled again in order to
    # changes in values.yaml to be applied
    # TODO: Implement a better way to handle this
    # alertmanager:
    #   enabled: false
  valuesFrom:
    - kind: ConfigMap
      name: kube-prometheus-stack-alertmanager-configmap
      valuesKey: values.yaml
      optional: false
