apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 72.6.4
      sourceRef:
        kind: HelmRepository
        name: prometheus-charts
        namespace: flux-system
  values:
    grafana:
      enabled: false
    prometheus:
      service:
        type: NodePort
      prometheusSpec:
        podMonitorSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        podMonitorSelector: {}
        ruleSelector: {}
        namespaceSelector:
          any: true
    alertmanager:
      service:
        type: NodePort
      config:
        route:
          group_by: ["namespace", "alertname"]
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 12h
          receiver: "null"
          routes:
            - receiver: discord
              matchers:
                - notifier = "discord"
        receivers:
          - name: discord
            discord_configs:
              - webhook_url:
                  valueFrom:
                    secretKeyRef:
                      name: prometheus-discord-notifications-webhook
                      key: webhook_url
          - name: "null"
