apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prometheus-discord-notifications-webhook
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-secrets-store
  target:
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: prometheus-discord-notifications-webhook
        property: webhook_url
