apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  upgrade:
    timeout: 10m
    remediation:
      retries: 3
      remediateLastFailure: true
  interval: 10m
  chart:
    spec:
      chart: grafana
      version: 8.10.2
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  values:
    grafana.ini:
      server:
        domain: private-k8s.cristobalszk.dev
        root_url: https://private-k8s.cristobalszk.dev/grafana
        serve_from_sub_path: true
    service:
      type: NodePort
      nodePort: 30001
    persistence:
      enabled: true
      size: 1Gi
