apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: grafana
      version: 8.6.1
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  values:
    grafana.ini:
      server:
        domain: hello-world.example
        root_url: http://hello-world.example/grafana
        serve_from_sub_path: true
    service:
      type: NodePort
      nodePort: 30001
    readinessProbe:
      httpGet:
        path: /api/health
        port: 80
      initialDelaySeconds: 60
    livenessProbe:
      httpGet:
        path: /api/health
        port: 80
      initialDelaySeconds: 60
      timeoutSeconds: 30
      failureThreshold: 10
    persistence:
      enabled: true
      size: 1Gi
