apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-service-secrets
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-secrets-store
  target:
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: auth-service-secrets
        property: DB_URL
    - extract:
        key: auth-service-secrets
        property: PORT
    - extract:
        key: auth-service-secrets
        property: CF_POLICY_AUD
