apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dual-role
  namespace: kafka
  labels:
    strimzi.io/cluster: k8s-local-cluster
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 2Gi
        deleteClaim: false
        kraftMetadata: shared
  resources:
    limits:
      memory: 1Gi
      cpu: 1
    requests:
      memory: 64Mi
      cpu: 0.1
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: k8s-local-cluster
  namespace: kafka
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.9.0
    metadataVersion: 3.9-IV0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9095
        type: nodeport
        tls: false
        configuration:
          preferredNodePortAddressType: Hostname
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  entityOperator:
    topicOperator:
      resources:
        limits:
          memory: 384Mi
          cpu: 0.5
        requests:
          memory: 64Mi
          cpu: 0.1
    userOperator:
      resources:
        limits:
          memory: 384Mi
          cpu: 0.5
        requests:
          memory: 64Mi
          cpu: 0.1
