apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: local-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.9.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: nodeport
        port: 31090
        type: nodeport
        tls: false
        authentication:
          type: scram-sha-512
    storage:
      type: persistent-claim
      size: 2Gi
      deleteClaim: false
    config:
      log:
        retention:
          ms: 259200000 # 72 hours
          bytes: 1073741824 # 1 GiB
    resources:
      requests:
        memory: 64Mi
        cpu: 0.1
      limits:
        memory: 1Gi
        cpu: 1
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 2Gi
      deleteClaim: false
    resources:
      requests:
        memory: 64Mi
        cpu: 0.1
      limits:
        memory: 1Gi
        cpu: 1
  entityOperator:
    topicOperator: {}
    userOperator: {}
