apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: strimzi-kafka-operator
  namespace: kafka
spec:
  interval: 5m
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: 0.45.0
      sourceRef:
        kind: HelmRepository
        name: strimzi-charts
        namespace: flux-system
  values:
    watchNamespaces:
      - kafka
