apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: strimzi-kafka-operator
  namespace: kafka
spec:
  interval: 10m
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: 0.50.1
      sourceRef:
        kind: HelmRepository
        name: strimzi-charts
        namespace: flux-system
  values:
    replicas: 1
    watchAnyNamespace: false
    watchNamespaces: []
    resources:
      limits:
        memory: 384Mi
        cpu: 1
      requests:
        memory: 64Mi
        cpu: 0.1
