apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-notifier-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-notifier-pod
  template:
    metadata:
      labels:
        app: discord-notifier-pod
    spec:
      containers:
        - image: ghcr.io/crisszkutnik/discord-notifier:1.1.0
          imagePullPolicy: IfNotPresent
          name: discord-notifier-container
          resources:
            requests:
              memory: "64Mi"
              cpu: 0.1
            limits:
              memory: "512Mi"
              cpu: 0.5
          ports:
            - containerPort: 3000
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-notifier-secret
                  key: DISCORD_TOKEN
