apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: discord-notifier-secrets
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-secrets-store
  target:
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: discord-notifier-secrets
        property: DISCORD_TOKEN
