apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: discord-notifier-servicemonitor
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: discord-notifier-pod
  endpoints:
    - port: http
