apiVersion: v1
kind: Service
metadata:
  name: discord-notifier-service
  namespace: default
spec:
  selector:
    app: discord-notifier-pod
  ports:
    - name: http
      port: 3000
      targetPort: 3000
