- name: Copy K3s service file
  register: k3s_service
  template:
    src: "k3s.service.j2"
    dest: "/etc/systemd/system/k3s.service"
    owner: orangepi
    mode: 0644

- name: Enable and check K3s service
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Wait for node-token
  wait_for:
    path: "{{ k3s_server_location }}/server/node-token"

- name: Read node-token from master
  slurp:
    path: "{{ k3s_server_location }}/server/node-token"
  register: node_token

- name: Replace https://localhost:6443 by https://master-ip:6443
  command: >-
    k3s kubectl config set-cluster default
      --server=https://{{ master_ip }}:6443
  changed_when: true

- name: Create hostname value
  set_fact:
    hostname: "cluster-master-{{groups['master'].index(inventory_hostname)}}"

- name: Change hostname
  hostname:
    name: "{{ hostname }}"
    use: "debian"

- name: Print hostname
  debug:
    msg: "{{ hostname }}"
