apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: server-secrets
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-secrets-store
  target:
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: server-secrets
        property: DB_URL
    - extract:
        key: server-secrets
        property: GOOGLE_API_KEY
