apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord-bot
  namespace: flux-system
spec:
  type: discord
  secretRef:
    name: flux-notifications-discord-webhook
