apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flux-notifications
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-secrets-store
  target:
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: flux-notifications
        property: DISCORD_WEBHOOK_URL
