apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: source-controller-service-monitor
  namespace: flux-system
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: source-controller
  endpoints:
    - port: http-prom
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kustomize-controller-service-monitor
  namespace: flux-system
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: kustomize-controller
  endpoints:
    - port: http-prom
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: helm-controller-service-monitor
  namespace: flux-system
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: helm-controller
  endpoints:
    - port: http-prom
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notification-controller-service-monitor
  namespace: flux-system
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: notification-controller
  endpoints:
    - port: http-prom
