apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: security
spec:
  interval: 10m
  chart:
    spec:
      chart: external-secrets
      version: 0.10.4
      sourceRef:
        kind: HelmRepository
        name: external-secrets-charts
        namespace: flux-system
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: 1password-secrets-store
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.security.svc.cluster.local:8080
      vaults:
        K3s_cluster: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: external-secrets-operator-op-access-token
            key: token
