apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: security
spec:
  interval: 10m
  chart:
    spec:
      chart: external-secrets
      version: 0.14.4
      sourceRef:
        kind: HelmRepository
        name: external-secrets-charts
        namespace: flux-system
