apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: expenses-api-secrets
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-secrets-store
  target:
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: expenses-save-api
        property: CREDENTIALS_BASE64
    - extract:
        key: expenses-save-api
        property: SPREADSHEET_ID
    - extract:
        key: expenses-save-api
        property: DB_URL
