apiVersion: batch/v1
kind: CronJob
metadata:
  name: dollar-data-to-google-sheets-etl-cronjob
  namespace: default
spec:
  schedule: "0 18 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  timeZone: "America/Argentina/Buenos_Aires"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 259200
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: dollar-data-to-google-spreadsheets-etl
              image: ghcr.io/crisszkutnik/dollar-data-to-google-spreadsheets-etl:1.1.1
              imagePullPolicy: IfNotPresent
              env:
                - name: SHEET_ID
                  valueFrom:
                    secretKeyRef:
                      name: dollar-data-to-google-sheets-etl-secrets
                      key: SHEET_ID
                - name: SERVICE_ACCOUNT_EMAIL
                  valueFrom:
                    secretKeyRef:
                      name: dollar-data-to-google-sheets-etl-secrets
                      key: SERVICE_ACCOUNT_EMAIL
                - name: SERVICE_ACCOUNT_KEY
                  valueFrom:
                    secretKeyRef:
                      name: dollar-data-to-google-sheets-etl-secrets
                      key: SERVICE_ACCOUNT_KEY
                - name: KEY_BASE64
                  value: "true"
                - name: NOTIFICATION_SERVICE_URL
                  value: "http://discord-notifier-service.default.svc.cluster.local:3000"
                - name: DISCORD_NOTIFICATION_CHANNEL_ID
                  valueFrom:
                    secretKeyRef:
                      name: dollar-data-to-google-sheets-etl-secrets
                      key: DISCORD_NOTIFICATION_CHANNEL_ID
