apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dollar-data-to-google-sheets-etl-secrets
  namespace: default;
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-secrets-store
  target:
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: dollar-data-to-google-spreadsheets-etl-secrets
        property: SERVICE_ACCOUNT_KEY
    - extract:
        key: dollar-data-to-google-spreadsheets-etl-secrets
        property: SERVICE_ACCOUNT_EMAIL
    - extract:
        key: dollar-data-to-google-spreadsheets-etl-secrets
        property: SHEET_ID
    - extract:
        key: dollar-data-to-google-spreadsheets-etl-secrets
        property: DISCORD_NOTIFICATION_CHANNEL_ID
