apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: telegram-bot-secrets
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-secrets-store
  target:
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: telegram-bot
        property: TELEGRAM_BOT_TOKEN
