apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: 1password-connect
  namespace: security
spec:
  interval: 10m
  chart:
    spec:
      chart: connect
      version: 1.16.0
      sourceRef:
        kind: HelmRepository
        name: 1password-charts
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: op-credentials
      valuesKey: op-credentials
      targetPath: connect.credentials_base64
