---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: metallb-crd-source
  namespace: flux-system
spec:
  interval: 60m
  url: https://github.com/metallb/metallb.git
  secretRef:
    name: flux-system
  ref:
    tag: v0.14.5
  ignore: |
    # exclude all
    /*
    # path to crds
    !/config/crd/bases
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-crds
  namespace: flux-system
spec:
  interval: 30m
  prune: true
  sourceRef:
    kind: GitRepository
    name: metallb-crd-source
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: ipaddresspools.metallb.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: l2advertisements.metallb.io
