apiVersion: v1
kind: Service
metadata:
  name: finance-market-data-puller-service
  namespace: default
  labels:
    app: financial-market-data-puller
spec:
  type: NodePort
  selector:
    app: finance-market-data-puller-pod
  ports:
    - name: web
      nodePort: 30003
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: prom-metrics
      nodePort: 30004
      port: 9400
      protocol: TCP
      targetPort: 9400
