apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: finance-market-data-puller
spec:
  selector:
    matchLabels:
      app: financial-market-data-puller
  endpoints:
    - port: prometheus-metrics
