apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: finance-market-data-puller
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: financial-market-data-puller
  endpoints:
    - port: prom-metrics
