- name: "Set IP address var"
  set_fact:
    host_ip_address: "{{ ansible_default_ipv4.address }}"

- name: "Retrieve IP from INI file"
  set_fact:
    target_ip_address: "{{ lookup('ini', '{{ host_ip_address }} section=ip_map file=../../host_map.ini' ) }}"

- name: Print new IP
  debug:
    msg: "{{ target_ip_address }}"

- name: Copy netplan
  template:
    src: "netplan.j2"
    dest: "/etc/netplan/orangepi-default.yaml"
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Apply and reload static IP address
  command: netplan apply
  become: true
  async: 100
  poll: 0
