- name: Copy K3s service file
  template:
    src: "k3s.service.j2"
    dest: "/etc/systemd/system/k3s.service"
    owner: orangepi
    mode: 0755

- name: Create hostname value
  set_fact:
    hostname: "cluster-node-{{groups['nodes'].index(inventory_hostname)}}"

- name: Change hostname
  hostname:
    name: "{{ hostname }}"
    use: "debian"

- name: Print hostname
  debug:
    msg: "{{ hostname }}"

- name: Enable and check K3s service
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes
