apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: expenses-receiver
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-secrets-store
  target:
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: expenses-receiver-secrets
        property: KAFKA_BROKERS
    - extract:
        key: expenses-receiver-secrets
        property: CLIENT_SECRET
