apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-node
  name: hello-node
  namespace: default
spec:
  type: NodePort
  selector:
    app: hello-node
  ports:
    - nodePort: 30002
      port: 8080
      protocol: TCP
      targetPort: 8080
