apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: notification.new
  namespace: kafka
  labels:
    strimzi.io/cluster: k8s-local-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000 # 1 week
    segment.bytes: 1073741824 # 1 GiB
