apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  path: ./clusters/apps
  prune: true
  wait: true
  dependsOn:
    - name: repositories
  sourceRef:
    kind: GitRepository
    name: flux-system
