apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-config
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  path: ./clusters/core-config
  prune: true
  wait: true
  dependsOn:
    - name: repositories
    - name: core
  sourceRef:
    kind: GitRepository
    name: flux-system
