apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kafka
  namespace: flux-system
spec:
  interval: 10m
  path: ./
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  prune: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: kafka-config
        namespace: flux-system
