apiVersion: kustomize.config.k8s.io/v1beta2
kind: Kustomization
resources:
  - secret.yaml
  - release.yaml
postBuild:
  substituteFrom:
    - kind: Secret
      name: kafka-config
      namespace: flux-system
