apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kafka
  namespace: flux-system
spec:
  resources:
    - secret.yaml
    - release.yaml
  postBuild:
    substituteFrom:
      - kind: Secret
        name: kafka-config
        namespace: flux-system
