apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: kafka
      version: 31.5.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  values:
    controller:
      replicaCount: 1
      resources:
        limits:
          cpu: 0.5
          memory: 1Gi
        requests:
          cpu: 0.1
          memory: 64Mi
      persistence:
        enabled: true
        size: 512Mi
        storageClass: local-path
      extraConfig:
        logRetentionHours: 168 # 7 days
        logRetentionBytes: 1Gi
    externalAccess:
      enabled: true
      controller:
        service:
          type: NodePort
          nodePorts:
            - "30101"
