apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: kafka
      version: 31.5.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  values:
    # listeners:
    #   overrideListeners: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:30101
    #  advertisedListeners: INTERNAL://kafka.default.svc.cluster.local:9092,EXTERNAL://192.168.0.200:30101
    #  securityProtocolMap: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
    controller:
      replicaCount: 1
      resources:
        limits:
          cpu: 0.5
          memory: 1Gi
        requests:
          cpu: 0.1
          memory: 64Mi
      persistence:
        enabled: true
        size: 512Mi
        storageClass: local-path
      extraConfig:
        logRetentionHours: 168 # 7 days
        logRetentionBytes: 1Gi
    externalAccess:
      enabled: true
      controller:
        service:
          type: NodePort
          nodePorts:
            - "30101"
          externalIPs:
            - "192.168.0.200"
    # Had trouble trying to use 'secretKeyRef'
    sasl:
      client:
        users:
          - "someuser"
        passwords:
          - "somepassword"
