apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kafka-config
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-secrets-store
  target:
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: kafka-config
        property: telegram-bot-user
    - extract:
        key: kafka-config
        property: telegram-bot-password
