apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-pushgateway
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: prometheus-pushgateway
      version: 3.0.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-charts
        namespace: flux-system
  values:
    serviceMonitor:
      enabled: true
    service:
      type: NodePort
      nodePort: 32500
