apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-pushgateway
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: prometheus-pushgateway
      version: 2.15.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-charts
        namespace: flux-system
  values:
    serviceMonitor:
      enabled: true
      additionalLabels:
        # Have to add this label so kube-prometheus-stack scrapes the service monitor
        release: prometheus
    service:
      type: NodePort
      nodePort: 32500
