apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secrets-charts.yaml
  - metallb-charts.yaml
  - ingress-nginx-charts.yaml
  - grafana-charts.yaml
  - prometheus-charts.yaml
