apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-charts
  namespace: flux-system
spec:
  interval: 30m
  timeout: 5m
  url: https://prometheus-community.github.io/helm-charts
