apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: strimzi-charts
  namespace: flux-system
spec:
  type: "oci"
  interval: 30m
  timeout: 5m
  url: oci://quay.io/strimzi-helm
