apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: telegram-bot
  namespace: kafka
  labels:
    strimzi.io/cluster: local-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: notification.new
          patternType: literal
        operation: Read
