name: Scan credentials

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  scan-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Trufflehog
        uses: trufflesecurity/trufflehog@v3.79.0
