# Replace OrangePi Ubuntu version apt sources with Ubuntu ARM apt sources

- name: Copy Ubuntu ARM sources.list file
  become: true
  template:
    src: "sources.list.j2"
    dest: "/etc/apt/sources.list"
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Update sources
  command: apt update
  become: true

- name: Upgrade packages
  command: apt -y upgrade
  become: true
